name: Rustfmt

on:
  push:
    paths:
      - 'testrust/**'
      - 'lab1_rust_data_structures/**'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-testrust:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: testrust

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy,rustfmt
        override: true
    - name: Run format check
      run: make format

  build-lab1_rust_data_structures:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lab1_rust_data_structures

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy,rustfmt
        override: true
    - name: Run format check
      run: make format
