name: Tests

on:
  push:
    paths:
      - 'Testrust/**'
  pull_request:
      - 'Testrust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-Testrust:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: clippy,rustfmt
        override: true
    - name: Run tests
      run: make test
